### ISSUE TITLE
Error dalam mengambil nama file

### ISSUE THREAD

**Issue by adarmawan117** [bunnydreams/InstaSquare#4]
Jika saya punya file dengan nama "Anak baru 19.20.2022.jpg", maka outputnya akan menjadi "Anak baru 19.20" (ekstensi nya bukan .jpg, tapi .20).

**Comment by adarmawan117** [comment]
Solusinya saya merubah file "app.js" di baris 27 dan 28 menjadi
let squared_file =
    fileName.split(".").slice(0, -1).join(".") + "_squared." + fileName.split(".").pop();

**Comment by patrickxchong** [comment]
Hello, sudah fix dengan tolong @anthonydu !
